[package]
name = "lorapwn"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.4.0", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-stm32 = { version = "0.2.0", features = ["defmt", "stm32f303re", "memory-x", "time-driver-any", "exti"] }
embassy-usb = { version = "0.4.0", features = ["defmt"] }

cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
heapless = { version = "0.8", default-features = false }
aes = { version = "0.8", default-features = false }
ghash = { version = "0.5", default-features = false }
ctr = { version = "0.9", default-features = false }
chacha20poly1305 = { version = "0.10", default-features = false, features = ["alloc"] }
aead = { version = "0.5", default-features = false, features = ["alloc"] }
linked_list_allocator = "0.10"

[build-dependencies]
flip-link = "0.1"

[profile.dev]
debug = 2
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
